name: vectorizers_playground
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - -e .   # conda >= 4.4 only
    - python-dotenv
    - gdown
    - sentence-transformers
    - umap-learn
    - hdbscan
    - svd2vec        # for word benchmarking files
    - wordcloud
    - git+https://github.com/TutteInstitute/vectorizers
  - bokeh
  - click
  - colorcet     # umap-learn[plot]
  - coveralls
  - datashader   # umap-learn[plot]
  - fsspec
  - gensim
  - git>=2.5     # for git worktree template updating
  - holoviews    # umap-learn[plot]
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - nb_conda_kernels#<2.2.0  # nb_conda_kernels issue #158
  - pandas
  - pathlib
  - pytest
  - requests
  - scikit-image   # umap-learn[plot]
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sphinx
  - tensorflow>=2
  - tensorflow-hub
  - wheel
  - pytorch::pytorch
  - pytorch::torchvision
  - huggingface::tokenizers
  - huggingface::transformers>3.1